---
kind: pipeline
type: docker
name: default

steps:
  - name: local build
    image: qwe1/dind-ansible-molecule:2.9-root
    commands:
      - ls -lah
      - pwd
      - mkdir -p ~/.ansible/roles && cp -aR "$(pwd)" ~/.ansible/roles/richardskumat.ansible_role_user
      - molecule test
