---
image: qwe1/dind-ansible-molecule:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  ROLE_NAME: ansible-role-user
  GALAXY_USERNAME: richardskumat
  GALAXY_ROLENAME: ansible_role_user


services:
  - docker:dind

stages:
  - test

before_script:
  - ansible --version
  - molecule --version
  - cd ..
  - cp -aR $ROLE_NAME $GALAXY_USERNAME.$GALAXY_ROLENAME
  - cd $GALAXY_USERNAME.$GALAXY_ROLENAME

test_d9:
  stage: test
  variables:
    MOLECULE_DISTRO: "qwe1/docker-debian:9-molecule"
  script:
    - molecule test

test_d10:
  stage: test
  variables:
    MOLECULE_DISTRO: "qwe1/docker-debian:10-molecule"
  script:
    - molecule test

test_c7:
  stage: test
  variables:
    MOLECULE_DISTRO: "qwe1/docker-centos:7-molecule"
  script:
    - molecule test

test_c8:
  stage: test
  variables:
    MOLECULE_DISTRO: "qwe1/docker-centos:8-molecule"
  script:
    - molecule test
