---
image: qwe1/dind-ansible-molecule:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  ROLE_NAME: ansible-role-user
  GALAXY_USERNAME: richardskumat
  GALAXY_ROLENAME: ansible_role_user

services:
  - docker:dind

stages:
  - test

before_script:
  - ansible --version
  - molecule --version
  - cd ..
  - cp -aR $ROLE_NAME $GALAXY_USERNAME.$GALAXY_ROLENAME
  - cd $GALAXY_USERNAME.$GALAXY_ROLENAME

lint:
  stage: lint
  script:
    - ansible-lint

test_d11:
  stage: test
  variables:
    MOLECULE_DISTRO: "qwe1/docker-debian:11-molecule"
  script:
    - molecule test

test_d12:
  stage: test
  variables:
    MOLECULE_DISTRO: "qwe1/docker-debian:12-molecule"
  script:
    - molecule test

test_f38:
  stage: test
  variables:
    MOLECULE_DISTRO: "docker.io/qwe1/docker-el:f38"
  script:
    - molecule test

test_el9:
  stage: test
  variables:
    MOLECULE_DISTRO: "docker.io/qwe1/docker-el:al9"
  script:
    - molecule test
