---
image: qwe1/dind-ansible-molecule:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  ROLE_NAME: ansible-role-user
  GALAXY_USERNAME: richardskumat
  GALAXY_ROLENAME: ansible_role_user


services:
  - docker:dind

stages:
  - test

before_script:
  - ansible --version
  - molecule --version
  - cd ..
  - cp -aR $ROLE_NAME $GALAXY_USERNAME.$GALAXY_ROLENAME
  - cd $GALAXY_USERNAME.$GALAXY_ROLENAME

test_d9:
  stage: test
  variables:
    MOLECULE_DISTRO: "debian:9"
  script:
    - molecule test

test_d10:
  stage: test
  variables:
    MOLECULE_DISTRO: "debian:10"
  script:
    - molecule test

test_ub1604:
  stage: test
  variables:
    MOLECULE_DISTRO: "ubuntu:16.04"
  script:
    - molecule test

test_ub1804:
  stage: test
  variables:
    MOLECULE_DISTRO: "ubuntu:18.04"
  script:
    - molecule test

test_c7:
  stage: test
  variables:
    MOLECULE_DISTRO: "centos:7"
  script:
    - molecule test

test_c8:
  stage: test
  variables:
    MOLECULE_DISTRO: "centos:8"
  script:
    - molecule test
