---
kind: pipeline
type: docker
name: default

pipeline:
  local_test:
    image: qwe1/dind-ansible-molecule:root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ls -lah
      - pwd
      - mkdir -p ~/.ansible/roles && cp -aR "$(pwd)" ~/.ansible/roles/richardskumat.ansible_role_user
      - molecule test
