---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-debian:9}"
    pull: yes
    groups:
      - user
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      user:
        username: qwe
        password_var: hunter2
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
