---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-debian:10}"
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
scenario:
  name: default
