---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-docker.io/qwe1/docker-debian:12-molecule}"
    pre_build_image: true
    # tty: true
provisioner:
  name: ansible
verifier:
  name: ansible
