---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: quay.io/centos/centos:stream9
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
